name: literalura

services:
  screensound-database:
    container_name: literalura_db
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: literalura

